
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email_notifications'

receivers:
  - name: 'email_notifications'
    email_configs:
      - to: 'test@gmail.com'
        from: 'test@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'test@gmail.com'
        auth_password: 'pass'
        auth_identity: 'test@gmail.com'
        require_tls: true
